/**
 * Skills dictionary for keyword extraction. Each entry: canonical name, synonyms
 * (so "JS" counts for "JavaScript"), whether it's a technical skill (used for
 * skills coverage), and a specificity weight (generic terms count less).
 */
export interface SkillDef {
  term: string
  synonyms: string[]
  tech: boolean
  weight: number
}

type Row = [term: string, synonyms?: string[], tech?: boolean, weight?: number]

const ROWS: Row[] = [
  // Languages
  ['JavaScript', ['JS', 'ECMAScript', 'ES6']],
  ['TypeScript', ['TS']],
  ['Python'],
  ['Java'],
  ['C++', ['CPP']],
  ['C#', ['C Sharp', 'CSharp']],
  ['C'],
  ['Golang', ['Go language']],
  ['Rust'],
  ['Ruby'],
  ['PHP'],
  ['Swift'],
  ['Kotlin'],
  ['Scala'],
  ['R'],
  ['MATLAB'],
  ['SAS'],
  ['Julia'],
  ['Perl'],
  ['Bash', ['Shell scripting', 'Shell']],
  ['PowerShell'],
  ['SQL'],
  ['NoSQL'],
  ['HTML', ['HTML5']],
  ['CSS', ['CSS3']],
  ['Dart'],
  ['Elixir'],
  ['Haskell'],
  ['Solidity'],
  ['VBA'],
  // Web and frameworks
  ['React', ['React.js', 'ReactJS']],
  ['Next.js', ['NextJS']],
  ['Vue', ['Vue.js', 'VueJS']],
  ['Angular', ['AngularJS']],
  ['Svelte'],
  ['Node.js', ['Node', 'NodeJS']],
  ['Express', ['Express.js']],
  ['Django'],
  ['Flask'],
  ['FastAPI'],
  ['Spring', ['Spring Boot']],
  ['Ruby on Rails', ['Rails']],
  ['.NET', ['dotnet', 'ASP.NET']],
  ['Laravel'],
  ['GraphQL'],
  ['REST', ['RESTful', 'REST APIs', 'REST API']],
  ['gRPC'],
  ['Redux'],
  ['Tailwind', ['Tailwind CSS']],
  ['jQuery'],
  ['React Native'],
  ['Flutter'],
  ['iOS'],
  ['Android'],
  ['Electron'],
  ['WebSockets'],
  ['Webpack'],
  ['Vite'],
  // Data and ML
  ['Pandas'],
  ['NumPy'],
  ['SciPy'],
  ['scikit-learn', ['sklearn', 'scikit learn']],
  ['TensorFlow'],
  ['PyTorch'],
  ['Keras'],
  ['XGBoost'],
  ['Spark', ['Apache Spark', 'PySpark']],
  ['Hadoop'],
  ['Kafka', ['Apache Kafka']],
  ['Airflow', ['Apache Airflow']],
  ['dbt'],
  ['Snowflake'],
  ['BigQuery'],
  ['Redshift'],
  ['Databricks'],
  ['Tableau'],
  ['Power BI', ['PowerBI']],
  ['Looker'],
  ['Excel', ['Microsoft Excel', 'MS Excel']],
  ['Google Sheets'],
  ['Jupyter'],
  ['Machine learning', ['ML'], true, 0.9],
  ['Deep learning', [], true, 0.9],
  ['Natural language processing', ['NLP']],
  ['Computer vision', ['CV']],
  ['LLM', ['LLMs', 'Large language models']],
  ['Generative AI', ['GenAI', 'Gen AI']],
  ['Prompt engineering'],
  ['RAG', ['Retrieval augmented generation']],
  ['LangChain'],
  ['Statistics', ['Statistical analysis'], true, 0.8],
  ['A/B testing', ['AB testing', 'Experimentation']],
  ['Data analysis', ['Data analytics'], true, 0.7],
  ['Data visualization', ['Data viz'], true, 0.8],
  ['Data modeling', ['Data modelling']],
  ['ETL', ['ELT', 'Data pipelines']],
  ['Data warehousing', ['Data warehouse']],
  ['Regression', ['Linear regression', 'Logistic regression']],
  ['Time series'],
  ['Forecasting'],
  // Databases
  ['PostgreSQL', ['Postgres']],
  ['MySQL'],
  ['SQLite'],
  ['SQL Server', ['MSSQL', 'Microsoft SQL Server']],
  ['Oracle'],
  ['MongoDB', ['Mongo']],
  ['Redis'],
  ['Elasticsearch', ['Elastic']],
  ['DynamoDB'],
  ['Cassandra'],
  ['Firebase'],
  ['Supabase'],
  // Cloud and DevOps
  ['AWS', ['Amazon Web Services']],
  ['Azure', ['Microsoft Azure']],
  ['GCP', ['Google Cloud', 'Google Cloud Platform']],
  ['Docker'],
  ['Kubernetes', ['K8s']],
  ['Terraform'],
  ['Ansible'],
  ['CI/CD', ['CI CD', 'Continuous integration', 'Continuous delivery']],
  ['Jenkins'],
  ['GitHub Actions'],
  ['GitLab'],
  ['Git'],
  ['Linux', ['Unix']],
  ['Lambda', ['AWS Lambda']],
  ['S3'],
  ['EC2'],
  ['Serverless'],
  ['Microservices'],
  ['Distributed systems'],
  ['System design'],
  ['Observability'],
  ['Prometheus'],
  ['Grafana'],
  ['Datadog'],
  ['Nginx'],
  ['Networking', ['TCP/IP'], true, 0.8],
  ['Security', ['Cybersecurity', 'Information security'], true, 0.7],
  // Practices and tools
  ['Agile', [], false, 0.6],
  ['Scrum', [], false, 0.7],
  ['Kanban', [], false, 0.6],
  ['Jira'],
  ['Confluence'],
  ['Figma'],
  ['Unit testing', ['Testing', 'Test automation'], true, 0.8],
  ['Jest'],
  ['Cypress'],
  ['Playwright'],
  ['Selenium'],
  ['Pytest'],
  ['TDD', ['Test-driven development']],
  ['Object-oriented programming', ['OOP', 'Object oriented']],
  ['Data structures', ['Algorithms'], true, 0.8],
  ['API design', ['APIs', 'API'], true, 0.7],
  ['Salesforce'],
  ['SAP'],
  ['HubSpot'],
  ['Google Analytics', ['GA4']],
  ['SEO'],
  ['Product management', [], false, 0.8],
  ['Project management', [], false, 0.7],
  ['Stakeholder management', [], false, 0.6],
  ['Financial modeling', ['Financial modelling']],
  ['Accounting'],
  ['Communication', ['Communication skills'], false, 0.3],
  ['Leadership', [], false, 0.4],
  ['Problem solving', ['Problem-solving'], false, 0.3],
  ['Collaboration', ['Teamwork'], false, 0.3],
]

export const SKILLS: SkillDef[] = ROWS.map(([term, synonyms = [], tech = true, weight = 1]) => ({ term, synonyms, tech, weight }))

/** Single letters and short words that are too ambiguous unless written exactly. */
export const CASE_SENSITIVE = new Set(['C', 'R', 'S3', 'CV', 'ML', 'TS', 'JS', 'REST', 'API', 'Elastic', 'Node', 'Shell', 'Spring', 'Rails', 'Express', 'Testing', 'Security', 'Mongo', 'Oracle', 'Lambda', 'Elixir', 'Swift'])
